version: "3.0"

services:    
  server:
    container_name: server
    build: ./server
    tty: true
    expose:
    
  client:
    depends_on :
    - server
    container_name: client
    build: ./client
    tty: true
    network_mode: host